" Instal vim-plug if not yet
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'
Plug 'justinmk/vim-sneak'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'

call plug#end()

filetype plugin indent on    " required

set nocompatible              " be iMproved, required
filetype off                  " required

colorscheme gruvbox

let g:sneak#label = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'gruvbox'

let mapleader=' '

set laststatus=2

set t_Co=256
set bs=2

syntax on
filetype indent on
set autoindent
set number
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set ignorecase
set smartcase
set hlsearch
set incsearch
set termguicolors

inoremap jj <Esc>
nnoremap <silent> <C-l> :nohl<CR><C-l>

map <C-n> :NERDTreeToggle<CR>
